food/urls.py
from . import views
from django.urls import path
app_name = 'food'

urlpatterns = [
    # path('',views.index,name='index'),
    path('',views.IndexClassView.as_view(),name='index'),
    path('item/',views.item,name='item'),
    # path('<int:item_id>/',views.detail,name='detail'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    # path('add/',views.create_item,name='create_item'),
    path('add/',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

mysite/urls.py
from django.contrib import admin    
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
app_name = 'food'
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    # path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse # its user for getabsoluteuel for rediret page
# Create your models here.

class Item(models.Model):

    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.shutterstock.com/shutterstock/photos/2059817444/display_1500/stock-vector-no-image-available-photo-coming-soon-illustration-vector-2059817444.jpg")
    
    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_picture/', default='defaultimage.jpg')
    location = models.CharField(max_length=100) # PIP INSTALL PILLOW for pic

    def __str__(self):
        return self.user.username
    

    

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        

food/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# CRUD Operation
def index(request):
    item_list = Item.objects.all()
    return render(request,'food/index.html',{"item_list":item_list})

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('item_list')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    return render (request,'food/detail.html',{'item':item})


class FoodDetail(DetailView):
    model = Item;
    template_name = 'food/detail.html'
    


from .forms import ItemForm
def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})

# this is classbase view for create item
from django.views.generic.edit import CreateView

class CreateItem(CreateView):
    
    model = Item;

    fields = [ 'item_name','item_desc','item_price','item_image' ]
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    
    template_name = 'food/item-form.html'

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'item':item,'form':form}) 

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item}) 
    
# Authentication    
# signals     

users/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username} your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    
      <nav class="navbar nav-dark bg-dark " >
        <a href="{% url "food:index" %}" class="navbar-brand m-2 " style="color:white">Food App</a>
        <div class="navbar">
            
          <a href="#" class="nav-item nav-link">Menu Item</a>
          <a href="{% url 'food:create_item' %}" class="nav-item nav-link" >Add Item</a>
          <a href="#" class="nav-item nav-link">Delete Item</a>
          <a href="#" class="nav-item nav-link">View Item</a>

          {% if user.is_authenticated %}
          <a href="{% url "profile" %}" class="nav-link" style="background: none; border: none; padding: 0; cursor: pointer;">Profile</a>&nbsp;&nbsp;&nbsp;
          <form action="{% url 'logout' %}" method="post" style="display: inline;">
              {% csrf_token %}
              
              <button type="submit" class="nav-link" style="background: none; border: none; padding: 0; cursor: pointer;">
                  Logout
              </button>
          </form>
        {% else %}
          <a href="{% url 'login' %}" class="nav-link">Login</a>
          <a href="{% url 'register' %}" class="nav-link">Register</a>
        {% endif %}
        

          


        </div>
      </nav>

      {% if messages %}
          {% for msg in messages %}
              <div class="alert alert-{{ msg.tags }}">
                  {{ msg|safe }}
              </div>
          {% endfor %}
      {% endif %}

      {% block body %}
      {% endblock  %}
</body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" height="300px" alt="" class="card">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>₹{{ object.item_price }}</h3>

            <a href="{% url "food:delete_item" item.id %}">Delete</a>
        </div>        
    </div>
</div>

{% endblock body %}

food/templates/food/index.html
{% extends "food/base.html" %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
     </head>
  <body>

    {% block body %}
      {% for item in item_list %}
      <div class="row mb-4 align-items-center">
        <div class="col-md-2 offset-md-1 mt-2" >
            <img class="img-fluid rounded" height="100px" width="100px" src="{{ item.item_image }}" alt="Image" style="object-fit: cover;">
        </div>
        <div class="col-md-5">
            <h3>{{ item.item_name }}</h3>
            <h5 class="text-muted">{{ item.item_desc }}</h5>
            <h6 class="text-success">₹{{ item.item_price }}</h6>
            <h6 class="text-success">{{ item.user_name }}</h6>
        </div>
        <div class="col-md-2 text-center">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    
      {% endfor %}
    {% endblock %}




    
        
        {% comment %} <ul>
          <li>
            <a href="{% url 'food:detail' item.id %}">
              {{item.id}}--{{item.item_name}}
            </a>
          </li>
        </ul> {% endcomment %}
        

  </body>
</html>

food/templates/food/item-delete.html
<form action="" method="POST">
    {% csrf_token %}
    <h2>Are you sure you want tot delete {{item.item_name}} ?</h2>
    <button type="submit" >Delete</button>
</form>

food/templates/food/item-form.html
{% extends "food/base.html" %}


{% block body %}

<div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4 mt-5">
        <div class="card">
          <div class="card-header bg-info text-white">
            <div class="card-title text-center">
              Add item
            </div>
          </div>
          <div class="card-body ">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mt-3">
                    {{ form.item_name.label_tag }}
                    {{ form.item_name }}
                </div>
                <div class="mt-3">
                    {{ form.item_desc.label_tag }}
                    {{ form.item_desc }}
                </div>
                <div class="mt-3">
                    {{ form.item_price.label_tag }}
                    {{ form.item_price }}
                </div>
                <div class="mt-3">
                    {{ form.item_image.label_tag }}
                    {{ form.item_image }}
                </div>
                <button type="submit" class="btn btn-primary mt-3">Save</button>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock body %}


{% comment %} <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" >Save</button>
</form> {% endcomment %}

users/templates/users/login.html
{% extends "food/base.html" %}

{% block body %}

  {% if user.is_authenticated %}
    <h2>You are already logged in.</h2>
    <a href="{% url 'logout' %}">Logout</a>

  {% else %}
      <div class="container">
        <div class="row">
          <div class="col-md-4 offset-md-4 mt-5">
            <div class="card">
              <div class="card-header bg-info text-white">
                <div class="card-title text-center">
                  Login
                </div>
              </div>
              <div class="card-body ">
                <form method="POST">
                  {% csrf_token %}
                  {% for field in form  %}
                    <div class="form-group mt-2 ">
                      {{field.name}}
                      {{field}}
                    </div>
                  {% endfor %}
                  <button class="btn-info  mt-2" type="submit">Login</button>
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
          
  {% endif %}

{% endblock body %}

users/templates/users/logout.html
{% block body %}
  <div class="container mt-5 text-center">
    <h1>You are successfully logged out!</h1>
    <p><a href="{% url 'login' %}">Click here to log in again</a></p>
  </div>
{% endblock %}

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" alt="">

users/templates/users/register.html
{% extends "food/base.html" %}


{% block body %}

<div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4 mt-5">
        <div class="card">
          <div class="card-header bg-info text-white">
            <div class="card-title text-center">
              Register
            </div>
          </div>
          <div class="card-body ">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.name }} <br>
                        {{ field }}
                    </div>
                {% endfor %}
                <button class="btn-info mt-2" type="submit" >Signup</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock body %}